package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import edu.wpi.first.epilogue.Logged;
import edu.wpi.first.epilogue.Logged.Importance;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.util.ArrayUtil;
import frc.robot.util.CtreUtil;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* Swerve request reused by drive(ChassisSpeeds), e.g. for PathPlanner path-following */
    private final SwerveRequest.RobotCentric m_robotCentricDriveRequest = new SwerveRequest.RobotCentric()
            .withDriveRequestType(DriveRequestType.Velocity);

    /*
     * Supply current for all eight drive/steer motors, for the offline power analysis in
     * tools/power_analysis. The drivetrain has no IO layer, so unlike every other subsystem the
     * signals live directly on the subsystem.
     *
     * These are field initializers rather than constructor-body code deliberately: field
     * initializers run after super() returns, so getModules() is already populated, and this class
     * has three constructors that would otherwise each need the same call.
     *
     * Drive and steer are kept as separate series rather than one drivetrain total. They fail
     * differently - drive current tracks acceleration and pushing matches, steer current spikes on
     * direction reversals - and lumping them hides which one is actually eating the budget.
     */
    private final BaseStatusSignal[] m_driveSupplyCurrentSignals = createSupplyCurrentSignals(true);
    private final BaseStatusSignal[] m_steerSupplyCurrentSignals = createSupplyCurrentSignals(false);
    /* Both of the above in one array, so periodic() refreshes all sixteen in a single call. */
    private final BaseStatusSignal[] m_allSupplyCurrentSignals =
            ArrayUtil.concat(m_driveSupplyCurrentSignals, m_steerSupplyCurrentSignals);

    /* Cached by periodic(); module order matches getModules(): FL, FR, BL, BR. */
    private final double[] m_driveSupplyCurrentsAmps = new double[m_driveSupplyCurrentSignals.length];
    private final double[] m_steerSupplyCurrentsAmps = new double[m_steerSupplyCurrentSignals.length];
    private double m_totalSupplyCurrentAmps = 0.0;

    /**
     * Builds a supply current signal for each module's drive motor ({@code drive == true}) or steer
     * motor, and raises them off their Phoenix default rate - see
     * {@link CtreUtil#kCurrentSignalFrequencyHz} for why the default is useless here.
     */
    private BaseStatusSignal[] createSupplyCurrentSignals(boolean drive) {
        var modules = getModules();
        BaseStatusSignal[] signals = new BaseStatusSignal[modules.length];
        for (int i = 0; i < modules.length; i++) {
            signals[i] = drive
                    ? modules[i].getDriveMotor().getSupplyCurrent()
                    : modules[i].getSteerMotor().getSupplyCurrent();
        }
        CtreUtil.setCurrentSignalFrequency(signals);
        return signals;
    }


    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));

    /*
     * SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    volts -> setControl(m_steerCharacterization.withVolts(volts)),
                    null,
                    this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        ;

    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        ;

    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve
     *                                  drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz
     *                                  on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {

        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
                modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        ;
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    public Pose2d getPose() {
        return state().Pose;
    }

    public ChassisSpeeds getChassisSpeeds() {
        return state().Speeds;
    }

    /**
     * The drivetrain state. Prefer this over Phoenix's {@link #getState()} everywhere in robot code.
     *
     * <p>{@code getState()} is not a cheap accessor: every call is a JNI round trip, a lock
     * acquisition, and a rebuild of the state struct that allocates a fresh {@code Pose2d},
     * {@code Rotation2d}, {@code ChassisSpeeds}, and up to twelve {@code SwerveModuleState}/
     * {@code SwerveModulePosition} objects, since on a moving robot essentially every field differs
     * from the last call. Shot control, Epilogue logging, auto-align, and this class's own
     * periodic() all read the state every loop, so calling through meant ~60 short-lived objects
     * per loop purely as GC fodder. This holds the reference and re-reads it once, in periodic().
     *
     * <p><b>This is a live reference, not a snapshot.</b> Phoenix returns its own internal
     * {@code m_cachedState} instance, and the telemetry callback installed by
     * {@code registerTelemetry} rewrites that same instance from the odometry thread at up to
     * 250Hz. Two consequences:
     *
     * <ul>
     *   <li>Readers are <i>not</i> mutually consistent, and never were - the object changes
     *       underneath them. In practice this is benign: {@code Pose}, {@code Speeds},
     *       {@code RawHeading} and each module state are <i>replaced</i> with new immutable objects
     *       rather than mutated in place, so no individual value can be read torn. The worst case
     *       is reading {@code Pose} from one odometry tick and {@code Speeds} from the next, i.e.
     *       up to 4ms of skew. Don't add a reader that needs those two to be same-tick coherent;
     *       use {@link #getStateCopy()} if you ever do.
     *   <li>Data is fresher than a true snapshot would be - the odometry thread keeps updating it -
     *       so the once-per-loop refresh costs nothing in latency.
     * </ul>
     *
     * <p>Reads here do not hold {@code m_stateLock}, which the odometry thread holds while it
     * writes. That race predates this method - getState() locks only its own update, then hands the
     * caller the shared object to dereference unlocked - and is harmless for the reference-typed
     * fields above. {@code SuccessfulDaqs}/{@code FailedDaqs} are {@code int}, so they read
     * atomically too.
     *
     * <p>{@code Timestamp} and {@code OdometryPeriod} are the exception: they are {@code double},
     * and 64-bit reads are not atomic on the roboRIO's 32-bit JVM, so a concurrent odometry write
     * can in principle be read torn. {@link AutoAlign#initialize()} and
     * {@link AutoAlign#applyDriveRequest} read {@code Timestamp} to seed and step their rotation
     * profile, and they need {@code Pose}, {@code Speeds} and {@code Timestamp} to agree on a
     * single tick - which this method cannot promise. Those three call sites (the ones that assign
     * the {@code swerveState} field) therefore use {@link #getStateCopy()} instead, which clones
     * under the lock. Single-field reads such as {@code state().Pose} are fine here: a lone
     * reference read is atomic and needs no cross-field coherence.
     *
     * <p>The refresh happens at the <i>end</i> of {@link #periodic()}. AprilTag fusion lives in
     * {@code RealATVision}, which is constructed after this subsystem and so runs later in the
     * scheduler's registration order: it reads the state refreshed here, then calls
     * {@code addVisionMeasurement}, whose correction this method picks up on the next loop. The
     * ordering is belt-and-braces rather than load-bearing, given the odometry thread would
     * surface the correction within a tick anyway.
     */
    // @Logged(name = "State", importance = Importance.CRITICAL)
    public SwerveDriveState state() {
        if (m_state == null) {
            refreshState();
        }
        return m_state;
    }

    private SwerveDriveState m_state = null;

    /**
     * Re-reads the drivetrain state from Phoenix. Called once per loop from periodic(); see
     * {@link #state()} for why once is enough.
     */
    private void refreshState() {
        m_state = getState();
    }


    /**
     * Sets the supply current limit on every drive motor. Only ever called from
     * {@link frc.robot.util.currentlimit.CurrentLimitManager}'s background apply thread (see
     * {@link frc.robot.RobotCurrentLimits}), never from periodic() directly - a config-apply call
     * blocks waiting on a CAN response, which would stall the main loop if run there.
     *
     * <p>{@code CurrentLimitsConfigs} is a config *group*: applying one overwrites every field in
     * the group on the motor, including ones this call doesn't set, resetting them to their class
     * defaults. So the stator limit is re-asserted to {@link TunerConstants#kModuleSlipCurrents} on
     * every call here as well, even though this method only ever changes the supply limit.
     * Otherwise a dynamic supply-limit change would silently wipe out the slip-current-based
     * stator limit that TunerConstants configures. {@code kModuleSlipCurrents} is indexed in the
     * same order as {@link #getModules()} (FrontLeft, FrontRight, BackLeft, BackRight), so each
     * module keeps its own front/back slip current rather than all four being reset to one value.
     */
    public void setDriveSupplyCurrentLimit(double supplyCurrentLimitAmps) {
        var modules = getModules();
        for (int i = 0; i < modules.length; i++) {
            CurrentLimitsConfigs limits = new CurrentLimitsConfigs()
                .withStatorCurrentLimit(TunerConstants.kModuleSlipCurrents[i])
                .withStatorCurrentLimitEnable(true)
                .withSupplyCurrentLimit(supplyCurrentLimitAmps)
                .withSupplyCurrentLimitEnable(true);
            CtreUtil.reportIfNotOk("Drivetrain/Drive current limit",
                    modules[i].getDriveMotor().getConfigurator().apply(limits, Constants.kDynamicConfigTimeoutSeconds));
        }
    }

    public void drive(ChassisSpeeds speeds) {
        this.setControl(m_robotCentricDriveRequest
                .withVelocityX(speeds.vxMetersPerSecond)
                .withVelocityY(speeds.vyMetersPerSecond)
                .withRotationalRate(speeds.omegaRadiansPerSecond));
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }

        refreshSupplyCurrents();

        // Re-read last. Vision fusion now lives in RealATVision, a separate subsystem registered
        // after this one, so it consumes the state refreshed here and its addVisionMeasurement
        // calls land after this refresh -- the odometry thread surfaces the correction within a
        // tick either way. See state(): this is a live reference to Phoenix's own state object,
        // not a point-in-time snapshot.
        refreshState();
    }

    /**
     * Reads this loop's supply current for all eight motors in one batched refresh and caches it,
     * so the logged getters below are field reads rather than sixteen JNI calls.
     */
    private void refreshSupplyCurrents() {
        BaseStatusSignal.refreshAll(m_allSupplyCurrentSignals);

        double total = 0.0;
        for (int i = 0; i < m_driveSupplyCurrentsAmps.length; i++) {
            m_driveSupplyCurrentsAmps[i] = m_driveSupplyCurrentSignals[i].getValueAsDouble();
            total += m_driveSupplyCurrentsAmps[i];
        }
        for (int i = 0; i < m_steerSupplyCurrentsAmps.length; i++) {
            m_steerSupplyCurrentsAmps[i] = m_steerSupplyCurrentSignals[i].getValueAsDouble();
            total += m_steerSupplyCurrentsAmps[i];
        }
        m_totalSupplyCurrentAmps = total;
    }

    /** Per-module drive motor supply current, in getModules() order: FL, FR, BL, BR. */
    @Logged(name = "Drive/Supply Currents", importance = Importance.DEBUG)
    public double[] getDriveSupplyCurrentsAmps() {
        return m_driveSupplyCurrentsAmps;
    }

    /** Per-module steer motor supply current, in getModules() order: FL, FR, BL, BR. */
    @Logged(name = "Steer/Supply Currents", importance = Importance.DEBUG)
    public double[] getSteerSupplyCurrentsAmps() {
        return m_steerSupplyCurrentsAmps;
    }

    @Logged(name = "Drive/Supply Current Total", importance = Importance.CRITICAL)
    public double getDriveSupplyCurrentTotalAmps() {
        return ArrayUtil.sum(m_driveSupplyCurrentsAmps);
    }

    @Logged(name = "Steer/Supply Current Total", importance = Importance.CRITICAL)
    public double getSteerSupplyCurrentTotalAmps() {
        return ArrayUtil.sum(m_steerSupplyCurrentsAmps);
    }

    /** All eight motors combined. The drivetrain's single line in the power budget. */
    @Logged(name = "Supply Current Total", importance = Importance.CRITICAL)
    public double getTotalSupplyCurrentAmps() {
        return m_totalSupplyCurrentAmps;
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}
