package frc.robot.util;

import edu.wpi.first.math.geometry.Translation2d;

public class TurretFeedforward {

    /** Constant-force spring tension [N] */
    private final double springForceN;

    /** Rectangle half-width [m] */
    private final double halfWidthM;

    /** Rectangle half-height [m] */
    private final double halfHeightM;

    /** Turret center -> effective chain contact radius [m] */
    private final double turretRadiusM;

    /** Turret torque generated per volt [N*m/V] */
    private final double torquePerVolt;

    /** Angle offset between turret zero and chain geometry [rad] */
    private final double angleOffsetRad;


    public TurretFeedforward(
            double springForceN,
            double halfWidthM,
            double halfHeightM,
            double turretRadiusM,
            double torquePerVolt,
            double angleOffsetRad) {

        this.springForceN = springForceN;
        this.halfWidthM = halfWidthM;
        this.halfHeightM = halfHeightM;
        this.turretRadiusM = turretRadiusM;
        this.torquePerVolt = torquePerVolt;
        this.angleOffsetRad = angleOffsetRad;
    }


    /**
     * Calculates the point where a ray from the turret
     * center intersects the rectangular e-chain path.
     */
    public Translation2d getChainContactPoint(double turretAngleRad) {

        double theta = turretAngleRad + angleOffsetRad;

        double cos = Math.cos(theta);
        double sin = Math.sin(theta);

        double x;
        double y;

        /*
         * Determine whether the ray hits the vertical
         * or horizontal side of the rectangle.
         */
        if (Math.abs(cos) * halfHeightM
                >= Math.abs(sin) * halfWidthM) {

            // Hits left/right side
            x = Math.copySign(halfWidthM, cos);
            y = x * sin / cos;

        } else {

            // Hits top/bottom side
            y = Math.copySign(halfHeightM, sin);
            x = y * cos / sin;
        }

        return new Translation2d(x, y);
    }


    /**
     * Calculates the torque generated by the e-chain.
     */
    public double calculateTorque(double turretAngleRad) {

        Translation2d contact =
                getChainContactPoint(turretAngleRad);

        double x = contact.getX();
        double y = contact.getY();

        /*
         * The e-chain force is tangent to the
         * rectangular path at the contact point.
         *
         * Determine which side we're on and construct
         * the tangent direction.
         */
        double fx;
        double fy;

        if (Math.abs(x) >= halfWidthM - 1e-9) {

            // Vertical side -> force is primarily vertical
            fy = springForceN * Math.copySign(1.0, y);
            fx = 0.0;

        } else {

            // Horizontal side -> force is primarily horizontal
            fx = springForceN * Math.copySign(1.0, x);
            fy = 0.0;
        }

        /*
         * 2D cross product:
         *
         * tau = r x F
         *     = x * Fy - y * Fx
         */
        return x * fy - y * fx;
    }


    /**
     * Calculates the voltage feedforward.
     */
    public double calculate(double turretAngleRad) {

        double torque = calculateTorque(turretAngleRad);

        return torque / torquePerVolt;
    }
}